// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqxrwvhgdnxzumbrrplg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxeHJ3dmhnZG54enVtYnJycGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTUzNjEsImV4cCI6MjA2MzkzMTM2MX0.XtJxIccunytStPetqTIHg692m5bJZ3rTwVt5sMfMZwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);